[package]
name = "smaug"
version = "0.1.0"
authors = ["Matt Pruitt <matt@guitsaru.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "3.0.1"
log = "0.4"
regex = "1"
semver = "0.11"
zip = "0.5"
zip-extensions = "0.6.0"
