name: Publish to AUR

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  aur-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish AUR package
        # TODO: Change back to KSXGithub/github-actions-delpoy-aur
        uses: superfly/aur-releaser@main
        with:
          pkgname: smaug
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
